# Generated by Django 5.2.14 on 2026-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('scope', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
            ],
        ),
    ]
